import { defineConfig } from 'cspell';

const config = defineConfig({
  useGitignore: true,
  ignorePaths: ['supabase/types.ts'],
  words: [
    'signalist',
    'commitlint',
    'inngest',
    'supabase',
    'hotlist',
    'watchlist',
    'tradingview',
    'elon',
    'finnhub',
    'nodemailer',
    'cmdk',
    'cellspacing',
    'Segoe',
    'weburl',
    'docstrings',
    'debouncer',
    'cli',
    'zod',
    'arlgnv',
    'watchlists',
    'forex',
    'knip',
    'typegen',
    'env',
    'coderabbit',
    'coderabbitai',
    'shadcn',
    'oklch',
    'kbd',
    'tanstack',
  ],
});

export default config;
